### ISSUE TITLE
[FEAT] 과연 추가하기 (FriendAdd) UI 구현

### ISSUE THREAD

**Issue by hwiwonK** [DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori#51]
## 💡 Issue

<img width="654" alt="image" src="https://user-images.githubusercontent.com/67336936/180707813-b11ca51b-e449-471a-a9b8-a6e365e64018.png">
과연 추가하기 (FriendAdd) UI 구현
- 검색 초기 화면, 검색 결과 화면, 결과 없을 때 화면

## 📝  todo
- [x] 검색 초기 화면 구현
- [x] 검색 결과 화면 구현
- [x] 결과 없을 때 화면 구현
